package com.taobao.fanli.dao.model;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_at
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.click_at
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String clickAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_info
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String goodsInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.manager
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shop
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String shop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_number
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_price
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_state
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_type
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.income_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String incomeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.divide_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String divideRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String pay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.effect
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String effect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.finish_pay
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String finishPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.forecast_income
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String forecastIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.finish_time
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String moneyRatio;

    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.subsidy_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String subsidyRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.subsidy_money
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String subsidyMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.subsidy_type
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String subsidyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.plantform
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String plantform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.third_from
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String thirdFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_number
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.type_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.media_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.media_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String mediaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ad_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ad_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    private String adName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_at
     *
     * @return the value of order.create_at
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_at
     *
     * @param createAt the value for order.create_at
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.click_at
     *
     * @return the value of order.click_at
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getClickAt() {
        return clickAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.click_at
     *
     * @param clickAt the value for order.click_at
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setClickAt(String clickAt) {
        this.clickAt = clickAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_info
     *
     * @return the value of order.goods_info
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getGoodsInfo() {
        return goodsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_info
     *
     * @param goodsInfo the value for order.goods_info
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setGoodsInfo(String goodsInfo) {
        this.goodsInfo = goodsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_id
     *
     * @return the value of order.goods_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_id
     *
     * @param goodsId the value for order.goods_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.manager
     *
     * @return the value of order.manager
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.manager
     *
     * @param manager the value for order.manager
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shop
     *
     * @return the value of order.shop
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getShop() {
        return shop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shop
     *
     * @param shop the value for order.shop
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setShop(String shop) {
        this.shop = shop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_number
     *
     * @return the value of order.goods_number
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_number
     *
     * @param goodsNumber the value for order.goods_number
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setGoodsNumber(String goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_price
     *
     * @return the value of order.goods_price
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_price
     *
     * @param goodsPrice the value for order.goods_price
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_state
     *
     * @return the value of order.order_state
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_state
     *
     * @param orderState the value for order.order_state
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_type
     *
     * @return the value of order.order_type
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_type
     *
     * @param orderType the value for order.order_type
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.income_ratio
     *
     * @return the value of order.income_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getIncomeRatio() {
        return incomeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.income_ratio
     *
     * @param incomeRatio the value for order.income_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setIncomeRatio(String incomeRatio) {
        this.incomeRatio = incomeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.divide_ratio
     *
     * @return the value of order.divide_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getDivideRatio() {
        return divideRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.divide_ratio
     *
     * @param divideRatio the value for order.divide_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setDivideRatio(String divideRatio) {
        this.divideRatio = divideRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay
     *
     * @return the value of order.pay
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay
     *
     * @param pay the value for order.pay
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setPay(String pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.effect
     *
     * @return the value of order.effect
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getEffect() {
        return effect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.effect
     *
     * @param effect the value for order.effect
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setEffect(String effect) {
        this.effect = effect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.finish_pay
     *
     * @return the value of order.finish_pay
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getFinishPay() {
        return finishPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.finish_pay
     *
     * @param finishPay the value for order.finish_pay
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setFinishPay(String finishPay) {
        this.finishPay = finishPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.forecast_income
     *
     * @return the value of order.forecast_income
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getForecastIncome() {
        return forecastIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.forecast_income
     *
     * @param forecastIncome the value for order.forecast_income
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setForecastIncome(String forecastIncome) {
        this.forecastIncome = forecastIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.finish_time
     *
     * @return the value of order.finish_time
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.finish_time
     *
     * @param finishTime the value for order.finish_time
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setFinishTime(String finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money_ratio
     *
     * @return the value of order.money_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getMoneyRatio() {
        return moneyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money_ratio
     *
     * @param moneyRatio the value for order.money_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setMoneyRatio(String moneyRatio) {
        this.moneyRatio = moneyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.subsidy_ratio
     *
     * @return the value of order.subsidy_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getSubsidyRatio() {
        return subsidyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.subsidy_ratio
     *
     * @param subsidyRatio the value for order.subsidy_ratio
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setSubsidyRatio(String subsidyRatio) {
        this.subsidyRatio = subsidyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.subsidy_money
     *
     * @return the value of order.subsidy_money
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getSubsidyMoney() {
        return subsidyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.subsidy_money
     *
     * @param subsidyMoney the value for order.subsidy_money
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setSubsidyMoney(String subsidyMoney) {
        this.subsidyMoney = subsidyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.subsidy_type
     *
     * @return the value of order.subsidy_type
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getSubsidyType() {
        return subsidyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.subsidy_type
     *
     * @param subsidyType the value for order.subsidy_type
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setSubsidyType(String subsidyType) {
        this.subsidyType = subsidyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.plantform
     *
     * @return the value of order.plantform
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getPlantform() {
        return plantform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.plantform
     *
     * @param plantform the value for order.plantform
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setPlantform(String plantform) {
        this.plantform = plantform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.third_from
     *
     * @return the value of order.third_from
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getThirdFrom() {
        return thirdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.third_from
     *
     * @param thirdFrom the value for order.third_from
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setThirdFrom(String thirdFrom) {
        this.thirdFrom = thirdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_number
     *
     * @return the value of order.order_number
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_number
     *
     * @param orderNumber the value for order.order_number
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.type_name
     *
     * @return the value of order.type_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.type_name
     *
     * @param typeName the value for order.type_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.media_id
     *
     * @return the value of order.media_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.media_id
     *
     * @param mediaId the value for order.media_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.media_name
     *
     * @return the value of order.media_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getMediaName() {
        return mediaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.media_name
     *
     * @param mediaName the value for order.media_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setMediaName(String mediaName) {
        this.mediaName = mediaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ad_id
     *
     * @return the value of order.ad_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ad_id
     *
     * @param adId the value for order.ad_id
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setAdId(String adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ad_name
     *
     * @return the value of order.ad_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ad_name
     *
     * @param adName the value for order.ad_name
     *
     * @mbggenerated Sun Jun 03 16:30:12 CST 2018
     */
    public void setAdName(String adName) {
        this.adName = adName;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }
}